//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHangMerchant
    {
        public int MaChiTietDDHMerchant { get; set; }
        public Nullable<int> MaDDHMerchant { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    
        public virtual DonDatHangMerchant DonDatHangMerchant { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual TrangThaiGiaoHang TrangThaiGiaoHang { get; set; }
    }
}
